
version: '3.2'

services:

  logger:
    build: ./logs/
    image: umputun/docker-logger
    container_name: "logger"
    hostname: "logger"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

    environment:
      - LOG_FILES=true
      - LOG_SYSLOG=false
      - EXCLUDE=docker-logger
      - MAX_FILES=10
      - MAX_SIZE=50
      - MAX_AGE=20
      - DEBUG=false
    #            - TIME_ZONE=America/Chicago

    volumes:
      - ./logs:/srv/logs
      - /var/run/docker.sock:/var/run/docker.sock

  zoo:
    # build from Dockerfile
    image: confluentinc/cp-zookeeper:latest
    container_name: zoofororder
    restart: unless-stopped
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ./bootcamp/zoo/data:/data
      - ./bootcamp/zoo/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafkafororder
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./bootcamp/kafka/data:/lib/kafka/data
    depends_on:
      - zoo
      

  db:
    image: 'postgres:13.1-alpine'
    container_name: orderdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orderdb
  
  consumerorder:
    # build from Dockerfile
    container_name: consumerorder
    image: consumerorder
    build: ./consumerOrder/
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456
      - GMAIL_USER=jaymishptl@gmail.com
      - GMAIL_PASSWORD=dubxclrrxluaiimd
      
  producerorder:
    # build from Dockerfile
    container_name: producerorder
    image: producerorder
    build: ./producerOrder/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - consumerorder
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456
      - GMAIL_USER=jaymishptl@gmail.com
      - GMAIL_PASSWORD=dubxclrrxluaiimd
      - URL_TO_CONSUMER=http://consumerorder:8081/Order
  
  consumerorderkafka:
    # build from Dockerfile
    container_name: consumerorderkafka
    image: consumerorderkafka
    build: ./consumerOrderKafka/
    ports:
      - "8084:8084"
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456
      - GMAIL_USER=jaymishptl@gmail.com
      - GMAIL_PASSWORD=dubxclrrxluaiimd
      - bootstrap_servers=kafka:9092
      - KAFKA_JSON_GROUPID=orderjsongroup
      - KAFKA_JSON_NAME=order-json
      - KAFKA_UPDATE_NAME=order-update
      - KAFKA_UPDATE_GROUPID=orderupdategroup
      - KAFKA_STRING_NAME=order-string
      - KAFKA_STRING_GROUPID=orderstringgroup
      
  producerorderkafka:
    # build from Dockerfile
    container_name: producerorderkafka
    image: producerorderkafka
    build: ./producerOrderKafka/
    ports:
      - "8083:8083"
    depends_on:
      - db
      - kafka
      - consumerorderkafka
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456
      - GMAIL_USER=jaymishptl@gmail.com
      - GMAIL_PASSWORD=dubxclrrxluaiimd
      - bootstrap_servers=kafka:9092
      - KAFKA_JSON_GROUPID=orderjsongroup
      - KAFKA_JSON_NAME=order-json
      - KAFKA_UPDATE_NAME=order-update
      - KAFKA_UPDATE_GROUPID=orderupdategroup
      - KAFKA_STRING_NAME=order-string
      - KAFKA_STRING_GROUPID=orderstringgroup
  
